# Generated by Django 4.2.5 on 2026-04-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_alter_medico_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('periodo', models.CharField(choices=[('M', 'Manhã (07:00)'), ('T', 'Tarde (13:00)'), ('N', 'Noite (19:00)')], max_length=1)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
                'unique_together': {('data', 'periodo')},
            },
        ),
    ]
