# Generated by Django 4.2.5 on 2026-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='status',
            field=models.CharField(choices=[('P', 'Agendado'), ('C', 'Concluído'), ('F', 'Faltou')], default='P', max_length=1),
        ),
    ]
