# Generated by Django 4.2.5 on 2026-04-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantoes', '0002_plantao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], default='P', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('medico_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to='medicos.medico')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='medicos.medico')),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='plantoes.plantao')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMudanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
